### ISSUE TITLE
Dashboards - invalid value for grafana.0.folder (must be a valid folder id)

### ISSUE THREAD

**Issue by garutilorenzo** [coralogix/terraform-provider-coralogix#147]
If we try to set the folder  id we get this error:

> invalid value for grafana.0.folder (must be a valid folder id)

```
resource "coralogix_hosted_dashboard" dashboard {
  grafana {
    config_json = templatefile("${path.module}/dashboard_templates/high_level.tpl", {
        common_prefix = var.common_prefix
    })
    overwrite = true
    folder = var.grafana_folder_id
  }
}
```

From the ui I see this from the url of the dashboard:

https://coralogix-url/#/grafana/dashboards/f/V04RZuWSk/test-dashboard.
And I guess that the folder id is "V04RZuWSk", but I found on the provider code that the ID must match a regexp that wants the id as integer, but from the doc it can be a string https://registry.terraform.io/providers/coralogix/coralogix/latest/docs/resources/hosted_dashboard#folder

**Comment by garutilorenzo** [comment]
https://github.com/coralogix/terraform-provider-coralogix/blob/3170998726152c65953142f8d133f3fc9e1d5811/coralogix/resource_hosted_dashboard.go#L22

**Comment by OrNovo** [comment]
@garutilorenzo Let me know if 1.8.16 works fine

**Comment by garutilorenzo** [comment]
@OrNovo now we have the following error:

>  Error: error parsing folder: strconv.ParseInt: parsing "V04RZuWSk": invalid syntax

It's not clear to us how we can find the folder id from the UI.
This is where the code fails now:

https://github.com/coralogix/terraform-provider-coralogix/blob/9e08319ef4404aa0293d0d561ceab6f0daac3077/coralogix/resource_hosted_dashboard.go#L259C23-L259C39

**Comment by OrNovo** [comment]
@garutilorenzo I think that the string that you see in the url is the UID, and you need the folderID.
I'm not sure what is the best option to get it, but I managed to see it in the url of the dashboard (i.e. - https://terraform.app.eu2.coralogix.com/#/grafana/dashboard/new?**folderId=42298**&orgId=42)

**Comment by garutilorenzo** [comment]
@OrNovo this is what I see from the UI:

![image](https://github.com/coralogix/terraform-provider-coralogix/assets/4757326/293c1b64-aeaf-4a5c-9f8d-76219c997122)

I cannot find any url with the folderId.
Even if i create a new dashboard, I cannot find the floder id in the url:
![image](https://github.com/coralogix/terraform-provider-coralogix/assets/4757326/3887b1fd-7d7f-40d7-a0d3-6a5b150729bd)

**Comment by OrNovo** [comment]
@garutilorenzo Try to create/open a dashboard inside it
<img width="660" alt="image" src="https://github.com/coralogix/terraform-provider-coralogix/assets/108669655/9fc8847c-f84f-44b4-9157-354d15c27502">

**Comment by garutilorenzo** [comment]
> @garutilorenzo Try to create/open a dashboard inside it <img alt="image" width="660" src="https://user-images.githubusercontent.com/108669655/272217484-9fc8847c-f84f-44b4-9157-354d15c27502.png">

Ok..
![image](https://github.com/coralogix/terraform-provider-coralogix/assets/4757326/de57907e-96f6-4310-b871-1e494d7b36ac)
If I try to create a new dashboard inside the folder the url shows finally the dashboard id, not really easy to find :disappointed_relieved:

**Comment by OrNovo** [comment]
@garutilorenzo we will add support for folder-uid also

**Comment by garutilorenzo** [comment]
@OrNovo 

> @garutilorenzo Try to create/open a dashboard inside it <img alt="image" width="660" src="https://user-images.githubusercontent.com/108669655/272217484-9fc8847c-f84f-44b4-9157-354d15c27502.png">

@OrNovo this trick is not working every time. To find the folder id the only way I have found that always work is to inspect the network calls via browser

**Comment by OrNovo** [comment]
@garutilorenzo We are now supporting folder id/uuid and also added support for grafana_folder
