### ISSUE TITLE
coralogix_tco_policy_logs value conversion error

### ISSUE THREAD

**Issue by leoffj** [coralogix/terraform-provider-coralogix#155]
### Affected Resource(s)

* coralogix_tco_policy_logs

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_providers {
    coralogix = {
      source  = "coralogix/coralogix"
      version = "~> 1.8.17"
    }
  }
  required_version = "1.5.4"
}

provider "coralogix" {
  api_key = xxxxxxxxx
  env     = "EUROPE2"
}

locals {
  test = [{
    rule_type : "includes"
    names : ["-dev"]
  }]
}

resource "coralogix_tco_policy_logs" "tco_policy" {
  count = 1

  name        = "test"
  priority     = "medium"
  order        = count.index + 1
  severities   = ["debug", "verbose", "info", "error", "warning", "critical"]
  applications = local.test[count.index] # gives error
#  applications = local.test[0]                 # works
}
```

### Expected Behavior

I would expect the resource to apply properly, without throwing any error.

### Actual Behavior

A plan or apply fails before refreshing state, with the following message:

│ Error: Value Conversion Error
│ 
│   with coralogix_tco_policy_logs.tco_policy,
│   on coralogix_tco.tf line 118, in resource "coralogix_tco_policy_logs" "tco_policy":
│  118:   applications = local.test[count.index]
│ 
│ An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the following to the provider developer:
│ 
│ Received unknown value, however the target type cannot handle unknown values. Use the corresponding `types` package type or a custom type that handles unknown values.
│ 
│ Path: applications
│ Target Type: *coralogix.TCORuleModel
│ Suggested Type: basetypes.ObjectValue

If the "count.index" is instead hardcoded to 0, it works. The issue prevents me from creating multiple tco policy rules with configuration from a yaml file.

### Steps to Reproduce

1. `terraform plan`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by OrNovo** [comment]
Hi @leoffj.
Please let me know if v1.8.20 fixed it.

**Comment by leoffj** [comment]
Yes, it is working as expected now! Thanks a lot for the quick fix.
