### ISSUE TITLE
Missing documentation for importing existing resources

### ISSUE THREAD

**Issue by artlist-scottambrose** [coralogix/terraform-provider-coralogix#158]
### Description

👋 - Most terraform resources that support being imported have a documentation snippet at the bottom of the docs page (for example https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami)

It would be great to see these added for this provider as the lack of it suggests resources don't support being imported when some of them actually do. The examples are also helpful for understanding the format of the id to use in the import which isn't always obvious.

Thanks 👍

**Comment by madianas21** [comment]
I tried importing `coralogix_grafana_folder`, but it does not work. So importing is not working at all probably.
