### ISSUE TITLE
Error creating standard alert with more_than condition

### ISSUE THREAD

**Issue by chris468** [coralogix/terraform-provider-coralogix#180]
### Affected Resource(s)

* coralogix_alert

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "coralogix_alert" "test_failure" {
  name     = "test failure"
  severity = "Critical"

  show_in_insights {
    notify_on                   = "Triggered_and_resolved"
    retriggering_period_minutes = 5
  }

  standard {
    applications = [
      "default"
    ]
    subsystems = [
      "tests"
    ]
    search_query = "name:TestResult NOT failed:[0, 2}"
    condition {
      # less_than         = false
      more_than         = true
      evaluation_window = "Rolling"
      time_window       = "5Min"
      threshold         = 0
      group_by          = []
      manage_undetected_values {
        enable_triggering_on_undetected_values = true
        auto_retire_ratio                      = "5Min"
      }
    }
  }

  notifications_group {
    notification {
      email_recipients = [] # each.value.email_recipients
    }
  }
}
```

### Debug Output

https://gist.github.com/chris468/efad130a98ac57b2400686bde6a4e968

### Panic Output

N/A

### Expected Behavior

Alarm should have been created

### Actual Behavior

Error saying that all of less_than, group_by, and manage_undetected_values must be specified:

```
Error: Missing required argument

  with coralogix_alert.test_failure,
  on standard_alert.tf line 25, in resource "coralogix_alert" "test_failure":
  25:       manage_undetected_values {

"standard.0.condition.0.manage_undetected_values": all of
`standard.0.condition.0.group_by,standard.0.condition.0.less_than,standard.0.condition.0.manage_undetected_values`
must be specified
```
I also tried specifying `less_than = true` instead of `more_than`, and it gave an error saying that all of more_than, group_by, and manage_undetected_values must be specified. And I tried specifying both `less_than = false` and `more_than = true`, and reported an error saying that only one of less_than or more_than can be specified.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

N/A

### References

* N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by OrNovo** [comment]
Hi @chris468 
_manage_undetected_values_ is relevant only in a case of _less_than_, and _evaluation_window_ is relevant only in a case of _more_than_.

**Comment by chris468** [comment]
Looks like I misread one of the error messages. I removed `manage_undetected_values` and plan succeeded for `more_than = true`. Thanks!
