### ISSUE TITLE
Error: Provider produced invalid plan

### ISSUE THREAD

**Issue by rohiteshwarbanda** [coralogix/terraform-provider-coralogix#187]
│ Provider "registry.terraform.io/coralogix/coralogix" planned an invalid
│ value for
│ coralogix_alert.standard_alert.standard[0].condition[0].group_by_key:
│ planned value cty.StringVal("") for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Unable to Read Previously Saved State for UpgradeResourceState
│ 
│   with coralogix_webhook.pager_duty_webhook,
│   on coralogix-alerts.tf line 1, in resource "coralogix_webhook" "pager_duty_webhook":
│    1: resource "coralogix_webhook" "pager_duty_webhook" {
│ 
│ There was an error reading the saved resource state using the current
│ resource schema.

Applied only one change, updated Coralogix for 1.4.4 to 1.10.4 version

 coralogix = {
      source  = "coralogix/coralogix"
      version = "~> 1.4.4"
    }
    coralogix = {
      source  = "coralogix/coralogix"
      version = "~> 1.10.4"
    }

### Affected Resource(s)

* coralogix_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by OrNovo** [comment]
@rohiteshwarbanda It would be helpful if you could share the .tf file your'e using.
