### ISSUE TITLE
Provider produced inconsistent result after apply if order changed in UI

### ISSUE THREAD

**Issue by chris468** [coralogix/terraform-provider-coralogix#193]
### Affected Resource(s)

* coralogix_tco_policy_logs

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_version = ">= 1.2.3"
  required_providers {
    coralogix = {
      source  = "coralogix/coralogix"
      version = ">=1.10"
    }
  }
}

provider "coralogix" {}

resource "coralogix_tco_policy_logs" "tco_policy_all_logs_to_low" {
  name       = "pawling-test debug to low - tf"
  priority   = "low"
  order      = 10
  severities = ["debug"]
}
```

### Debug Output

https://gist.github.com/chris468/9005c7c947badbcb36dc222bbd0c21aa

I forgot to redirect stderr when I captured the logs, but I was able to get the full debug output from console history for 2 of the files.

### Panic Output

N/A

### Expected Behavior

Ideally find a way to maintain the desired order, but at least error during apply rather than reporting inconsistent result.

### Actual Behavior

```
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to coralogix_tco_policy_logs.tco_policy_all_logs_to_low, provider "provider[\"registry.terraform.io/coralogix/coralogix\"]"
│ produced an unexpected new value: .order: was cty.NumberIntVal(10), but now cty.NumberIntVal(3).
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Steps to Reproduce

1. Check order of any existing policies: `grpcurl -H "Authorization: Bearer $CORALOGIX_API_KEY" -d '{}' ng-api-grpc.coralogix.com:443  com.coralogix.quota.v1.PoliciesService.GetCompanyPolicies | jq '.policies[] | {name: .name, order: .order}'`
    Result:
    ```
    {
      "name": "End to end test logs",
      "order": 1
    }
    {
      "name": "Debug, Verbose, and Info to Low",
      "order": 2
    }
    ```
1. `terraform apply | tee initial_apply.log`
1. Check order: `grpcurl -H "Authorization: Bearer $CORALOGIX_API_KEY" -d '{}' ng-api-grpc.coralogix.com:443  com.coralogix.quota.v1.PoliciesService.GetCompanyPolicies | jq '.policies[] | {name: .name, order: .order}'`
    Result: Terraform-created policy is order 3, even though 10 was specified in resource definition. But overall order is correct.
    ```
    {
      "name": "End to end test logs",
      "order": 1
    }
    {
      "name": "Debug, Verbose, and Info to Low",
      "order": 2
    }
    {
      "name": "pawling-test debug to low - tf",
      "order": 3
    }
    ``` 
1. Create another tco policy in the web UI, at the end.
1. Check order: `grpcurl -H "Authorization: Bearer $CORALOGIX_API_KEY" -d '{}' ng-api-grpc.coralogix.com:443  com.coralogix.quota.v1.PoliciesService.GetCompanyPolicies | jq '.policies[] | {name: .name, order: .order}'`
    Result: New policy has order 4, makes sense
    ```
    {
      "name": "End to end test logs",
      "order": 1
    }
    {
      "name": "Debug, Verbose, and Info to Low",
      "order": 2
    }
    {
      "name": "pawling-test debug to low - tf",
      "order": 3
    }
    {
      "name": "pawling-test verbose to low - ui",
      "order": 4
    }
    ```
1. In the web UI, move the manually created one above the one that was created by the stack: swap 3 and 4.
1. Check order: `grpcurl -H "Authorization: Bearer $CORALOGIX_API_KEY" -d '{}' ng-api-grpc.coralogix.com:443  com.coralogix.quota.v1.PoliciesService.GetCompanyPolicies | jq '.policies[] | {name: .name, order: .order}'`
    Result all policies orders are updated, starting w/ 0 instead of 1:
    ```
    {
      "name": "End to end test logs",
      "order": 0
    }
    {
      "name": "Debug, Verbose, and Info to Low",
      "order": 1
    }
    {
      "name": "pawling-test verbose to low - ui",
      "order": 2
    }
    {
      "name": "pawling-test debug to low - tf",
      "order": 3
    }
    ```
1. `terraform apply | tee second_apply.log`
    Result: Error in provider
    ```
    │ Error: Provider produced inconsistent result after apply
    │
    │ When applying changes to coralogix_tco_policy_logs.tco_policy_all_logs_to_low, provider "provider[\"registry.terraform.io/coralogix/coralogix\"]"
    │ produced an unexpected new value: .order: was cty.NumberIntVal(10), but now cty.NumberIntVal(3).
    │
    │ This is a bug in the provider, which should be reported in the provider's own issue tracker.

    ```

### Important Factoids

Our use case is that we want a default policy to set Info and below to 'Low', but we have an exception where we have one service that needs Info to be 'High'. We attempted to do this by setting the "default" policy w/ a high order, so that "exceptions" could be inserted above it.

When that didn't work, we tried to set the order to exactly what it should be. But the terraform resource will not allow an order of 0:  Change the order in the configuration to 0 and `terraform validate  | tee validate_order_0.log` reports:
```
│ Error: Invalid Attribute Value
│
│   with coralogix_tco_policy_logs.tco_policy_all_logs_to_low,
│   on main.tf line 15, in resource "coralogix_tco_policy_logs" "tco_policy_all_logs_to_low":
│   15:   order      = 0
│
│ Attribute order value must be at least 1, got: 0
```

### References

* #113 refers to multiple policies in the same terraform stack. But in these steps I use a single policy.
* #178 removed `coralogix_tco_policy_override`. I believe policy overrides would be a better solution to my use case. Is there a plan to support a policy override resource going forward?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by OrNovo** [comment]
Hi @chris468.
The current backend design prevents the ability to keep track on policies that where create outside of terraform, therefor it would be a bit difficult to implement your suggestion, even thought I agree it would be better to have this functionality.
However, the backend intend to release a new API where the tco-policies are implemented as a single list, thus solving the whole issues of parallelism, order, etc...

**Comment by chris468** [comment]
Thanks @OrNovo. Makes sense, that sounds like a better API. Do you know what is the timeframe for the new API?

Focusing less on policies created inside vs. outside terraform, just on the use case of "exceptions" to a "default" TCO policy: Is multiple TCO policies the best approach? Or are policy overrides better? Is the new API the reason the policy override resources were removed from the terraform provider?

In the meantime, we applied another workaround to prevent the terraform provider from erroring so that the rest of our stack will complete. We ignore the order for now:

```
resource "coralogix_tco_policy_logs" "tco_policy_all_logs_to_low" {
  name       = "pawling-test debug to low - tf"
  priority   = "low"
  order      = 10
  severities = ["debug"
  lifecycle {
    ignore_changes = [
      order
    ]
  }
}
```

**Comment by OrNovo** [comment]
I'm not sure about the time frame, I'll update.
Policy-overrides API will be removed regardless of terraform or API changes, so the best approach is to use only TCO policies.

**Comment by cameronwaterman** [comment]
Worth mentioning that this same issue affects the filter order for the `coralogix_sli` resource.

**Comment by OrNovo** [comment]
@cameronwaterman Not sure I understand your comment.

**Comment by cameronwaterman** [comment]
You receive the same error `Provider produced inconsistent result after apply` when deploying a `coralogix_sli` resource if the filter order was changed in the UI.

**Comment by cameronwaterman** [comment]
@OrNovo - I created a separate issue #211 to track the SLO behavior.
