### ISSUE TITLE
Application order of coralogix_sli filters is inconsistent

### ISSUE THREAD

**Issue by cameronwaterman** [coralogix/terraform-provider-coralogix#211]
### Affected Resource(s)

* coralogix_sli

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.5.7"
  required_providers {
    coralogix = {
      source  = "coralogix/coralogix"
      version = ">=1.10.3"
    }
  }
}

provider "coralogix" {}

resource "coralogix_sli" "test_sli_with_filters" {
  name            = "test_sli_with_filters"
  slo_period_type = "7_days"
  service_name    = "nidataframe"
  slo_percentage  = "99"
  metric_type     = "error"
  filters = [{
    compare_type = "is"
    field        = "tags.http.route"
    field_values = ["nidataframe/v1/tables", "nidataframe/v1/tables/{id}/data"]
    },
    {
      compare_type = "is"
      field        = "tags.http.well_formed_request"
      field_values = ["true"]
    },
    {
      compare_type = "is"
      field        = "tags.http.request.method"
      field_values = ["POST"]
  }]
}
```

### Debug Output

[Successful apply](https://gist.github.com/cameronwaterman/e08d4b5c995f5a6154ea4ad4d9962fc0)
[Failed apply](https://gist.github.com/cameronwaterman/11753751806834abfe94d4cb2bd37d18)

### Panic Output

N/A

### Expected Behavior

The order in which the filters are applied is consistent, avoiding the `Provider produced inconsistent result after apply` error.

### Actual Behavior

Subsequent applies without changes fail because the provider thinks the filter order has changed when it has not.

### Steps to Reproduce

1. `terraform apply` (succeed)
2. `terraform apply` (error)

### Important Factoids

N/A

### References

* #193 - The resulting error is the same as mentioned in this issue.

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by OrNovo** [comment]
@cameronwaterman Thanks for raising this issue.
After checking with backend team, we decided to change `filters` from `TypeList`  to `TypeSet`, because there's no logic difference regarding the filters order.
