### ISSUE TITLE
Runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by MileaRobertStefan** [coralogix/terraform-provider-coralogix#212]
### Affected Resource(s)

terraform-provider-coralogix_1.10.11

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

https://registry.terraform.io/providers/coralogix/coralogix/latest/docs/resources/alert

### Panic Output

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc5cf04]

goroutine 102 [running]:
terraform-provider-coralogix/coralogix.extractCreateAlertRequest(0xdf8474860?)
	terraform-provider-coralogix/coralogix/resource_coralogix_alert.go:1560 +0xb24
terraform-provider-coralogix/coralogix.resourceCoralogixAlertCreate({0x1225cc8, 0xc000b36330}, 0x0?, {0x102efc0?, 0xc000732990?})
	terraform-provider-coralogix/coralogix/resource_coralogix_alert.go:1444 +0x65
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0004caa80, {0x1225d00, 0xc0005e8840}, 0xd?, {0x102efc0, 0xc000732990})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:778 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004caa80, {0x1225d00, 0xc0005e8840}, 0xc000828000, 0xc0003cb200, {0x102efc0, 0xc000732990})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:909 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0004c60d8, {0x1225d00?, 0xc0007d22a0?}, 0xc000192460)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:1074 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x122e040?, 0xc0004c60d8?}}, {0x1225d00, 0xc0007d22a0}, 0x0?)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:37 +0x5a
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x1225c58?, {0x1225d00?, 0xc0005e8660?}, 0xc000192410)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x1b5
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0004b4280, {0x1225d00?, 0xc00073fcb0?}, 0xc000218310)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:857 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x1031fc0?, 0xc0004b4280}, {0x1225d00, 0xc00073fcb0}, 0xc0003ca780, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:503 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000572000, {0x1225d00, 0xc00073fc20}, {0x122b8f8, 0xc0005824e0}, 0xc0005afd40, 0xc0004d3e60, 0x198ae38, 0x0)
	google.golang.org/grpc@v1.60.0/server.go:1372 +0xe49
google.golang.org/grpc.(*Server).handleStream(0xc000572000, {0x122b8f8, 0xc0005824e0}, 0xc0005afd40)
	google.golang.org/grpc@v1.60.0/server.go:1783 +0x1031
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.60.0/server.go:1016 +0x68
created by google.golang.org/grpc.(*Server).serveStreams.func2
	google.golang.org/grpc@v1.60.0/server.go:1027 +0x12e

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by OrNovo** [comment]
Hi @MileaRobertStefan 
Can you please add steps to reproduce?

**Comment by MileaRobertStefan** [comment]
Yes, copy the code from the example and deploy it. I did nothing special beside adapt the values .

**Comment by OrNovo** [comment]
@MileaRobertStefan In a case of standard alert you need to set one of `less_than`, `more_than`, `more_than_usual`, or `immediately` to **true**.

**Comment by MileaRobertStefan** [comment]
@OrNovo  You are correct! Thank you! Could you do something about the error message? Like giving a null pointer exception is kind of scary :)

**Comment by OrNovo** [comment]
@MileaRobertStefan sure, will add on next release.
