### ISSUE TITLE
Add features for Dashboard sections like Coralogix UI

### ISSUE THREAD

**Issue by tifennlegoff** [coralogix/terraform-provider-coralogix#242]
### Description

When we're modify a dashboard on Coralogix UI, we can add Section, drag&drop graphs inside, add name and choose if we want to collapse it or not.
Is it possible to do the same thing with Terraform?

### New or Affected Resource(s)

* coralogix_dashboard

### Potential Terraform Configuration

Configuration could looks like this 

```hcl
resource "coralogix_dashboard" "my_dashboard" {
...
  layout = {
    sections = [
      {
        name      = "My section name"
        collapsed = false
        rows      = [
          {
...

```

With a structure like this on `coralogix/resource_coralogix_dashboard.go`

```hcl
type SectionModel struct {
	ID        types.String `tfsdk:"id"`
	Rows      types.List   `tfsdk:"rows"` //RowModel
	Name      types.String `tfsdk:"name"`
	Collapsed types.Bool   `tfsdk:"collapsed"`
}
```

### References

* #0000

### Community Note

* Please vote on this issue by adding a
  👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original
  issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tifennlegoff** [comment]
Is it possible to setup color like with UI too?

**Comment by celaus** [comment]
Hi, #243 includes these features

**Comment by tifennlegoff** [comment]
Hi @celaus! Great, thanks a lot!
