### ISSUE TITLE
Terraform apply don't works if dashboard folder is not present on backend

### ISSUE THREAD

**Issue by tifennlegoff** [coralogix/terraform-provider-coralogix#276]
Terraform apply failed because a folder in backend doesn't exist.

### Affected Resource(s)

* coralogix_dashboard

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
```

### Debug Output

```
##[debug]2024-10-07T12:58:00.380Z [WARN]  Planning encountered errors, so plan is not applyable
##[debug]
##[debug]Error: Dashboard folder "2b6fe432-b664-4479-9404-a61018faefc7" is in state, but no longer exists in Coralogix backend
##[debug]
##[debug]2b6fe432-b664-4479-9404-a61018faefc7 will be recreated when you apply
##[debug]2024-10-07T12:58:05.054Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
##[debug]2024-10-07T12:58:05.063Z [INFO]  provider: plugin process exited: plugin=.terraform/providers/registry.terraform.io/coralogix/coralogix/1.16.3/linux_amd64/terraform-provider-coralogix_1.16.3 id=4275
##[debug]2024-10-07T12:58:05.064Z [DEBUG] provider: plugin exited
##[debug]
##[debug]exitcode: 1
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

### Expected Behavior

Terraform apply should works, if folder doesn't exist on backend, Terraform module should create it.

### Actual Behavior

Terraform apply failed because a folder is not present on backend.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by celaus** [comment]
Hi, yes this is how terraform works your state grew stale and it drifted from remote.

**Comment by tifennlegoff** [comment]
Actually, I'm not sure, the debug say `2b6fe432-b664-4479-9404-a61018faefc7 will be recreated when you apply` so it should recreated it, not exited with `rpc error: code = Unavailable desc = error reading from server: EOF`.
I see that we're using the 1.6.3 version, I will try to use the latest version 🤞

**Comment by tifennlegoff** [comment]
So it didn't works with latest version... we will remove tfstate and all dashboards. It's weird because it can't be a drift, all of our modifications are `terraform apply` when the branch is merged to main, so we should have the same version between tfstate and code.
