### ISSUE TITLE
Terraform lose track of alarm if you manually change it

### ISSUE THREAD

**Issue by mark-serkiz** [coralogix/terraform-provider-coralogix#3]
Hi, using this module we faced an issue when terraform lose track of alarm if you manually change it. It. not always possible to handle all conditions via terraform(especially when using for each to create a bunch of similar alarms and later on adjust them separately in UI)

**Expected Behavior**
Able to change alarm settings and conditions manually or by terraform
**Current Behavior**
Terraform lose track of alarm after any changes due to unique id change
**Possible Solution**
**Steps to Reproduce**

1. Create alarm using terraform
2. Change anything in this alarm
3. Run terraform plan

**Comment by EldarAliiev** [comment]
Fixed in version v1.1.1.
