### ISSUE TITLE
Respect semver

### ISSUE THREAD

**Issue by Photonios** [coralogix/terraform-provider-coralogix#50]
### Description

Between 1.2.x and 1.3.x the configuration for alerts changed completely. The provider configuration also changed in a backwards incompatible manner.

In order to upgrade we had to remove all alerts and re-create them. Just adjusting the configuration was not enough and we got errors such as:

```
internal error for alert in Coralogix backend - rpc error: code = Internal desc = Attempt to decode value on failed cursor: DownField(alert)
```

I do not expect such massive, backwards incompatible changes when upgrading minor versions. For future releases, please create a new major release when there are backwards incompatible changes.

### New or Affected Resource(s)

* coralogix_alert

### Community Note

* Please vote on this issue by adding a
  👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original
  issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by oded-dd** [comment]
@Photonios thank you. We will make sure we comply to semver rules from now on. 
We will also provide clarification on the current version in the README file.

Let me know if you think anything else is required
