### ISSUE TITLE
Missing webhook resources after minor version upgrade

### ISSUE THREAD

**Issue by bohdanborovskyi-ma** [coralogix/terraform-provider-coralogix#65]
### Affected Resource(s)

* coralogix_webhook

### Terraform Configuration Files

```hcl
resource "coralogix_webhook" "coralogix_webhook" {
  alias      = "API webhook"
  type       = "pager_duty"
  pager_duty = pagerduty_service_integration.coralogix.integration_key // reference to another resource from same module 
}

resource "coralogix_webhook" "coralogix_webhook_email" {
  alias      = "Email webhook"
  type       = "email_group"
  email_group = [ pagerduty_service_integration.coralogix.integration_email ] // reference to another resource from same module  
}
```

### Expected Behavior

`coralogix_webhook` resource remains available for usage after the **minor version** upgrade.
No errors received from re-running the existing Terraform stacks.

### Actual Behavior

Dozens of our TF stacks just return errors due to invalid resource
```
Error: Invalid resource type
  on .terraform/modules/module_name/integration_cx.tf line 52, in resource "coralogix_webhook" "coralogix_webhook":
  52: resource "coralogix_webhook" "coralogix_webhook" {

The provider provider.coralogix does not support resource type
"coralogix_webhook".
```

### Steps to Reproduce

1. Upgrade the `coralogix` provider from 1.2.x to 1.3.x version
2. Try to run `terraform plan` over existing configuration

### References

* Seems like there's upcoming change which should bring back webhook resources - #51

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by OrNovo** [comment]
Hi @bohdanborovskyi-ma
As you mentioned, adding the webhook resource is still in progress.
This is related to backend stuff, so I’ll let you know when we have ET.

**Comment by OrNovo** [comment]
Hi @bohdanborovskyi-ma 
We added support for webhooks.
