### ISSUE TITLE
Webhook doc question

### ISSUE THREAD

**Issue by alonz** [coralogix/terraform-provider-coralogix#74]
Hello, 
I was waiting for the webhook support PR before upgrading to version 1.3.x. 
Now that the PR was merged I just want to verify that it is indeed supported since in the [doc](https://github.com/coralogix/terraform-provider-coralogix/blob/master/docs/index.md#coralogix-provider) it is still stated 

> Note! The Coralogix terraform registry has now been updated to v1.3.x. The new version contains many [breaking changes](https://github.com/coralogix/terraform-provider-coralogix/blob/master/CHANGELOG.md) and does not support webhooks. It should be configured by following the instructions below.

So just wanted to verify it's just a doc that needs a bit of update and not something else I'm missing.
Thanks

**Comment by OrNovo** [comment]
Hey @alonz.
This is a mistake in the doc.
You can find more info about webhooks here -[webhook.md](https://github.com/coralogix/terraform-provider-coralogix/blob/master/docs/resources/webhook.md) 
Thanks for the feedback.

**Comment by OrNovo** [comment]
We updated the docs, so I'm closing this issue.
